services:
  # PostgreSQL Database Service
  - type: database
    name: postgres
    ipAllowList: []  # Internal connections only

  # Redis Service for Sidekiq
  - type: redis
    name: sidekiq-redis
    ipAllowList: []  # Internal connections only
    plan: free
    maxmemoryPolicy: noeviction

  # Sidekiq Worker Service
  - type: worker
    name: sidekiq-worker
    runtime: ruby
    region: ohio
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec sidekiq
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false

  # Rails Web Service
  - type: web
    name: rails-web
    runtime: ruby
    region: ohio
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-production}
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false