database:
  - name: postgres
    ipAllowList: []  # Internal connections only

services:
  # Rails Web Service
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

  # Redis Service for Sidekiq
  - type: redis
    name: redis
    ipAllowList: []  # Internal connections only
    plan: free
    maxmemoryPolicy: noeviction