development:
  adapter: redis
  url: redis://localhost:6379/1  # Make sure Redis is running locally on port 6379
  channel_prefix: near_you_development

test:
  adapter: test

production:
  adapter: redis
  url: redis://red-cto7075umphs73cckorg:6379
  channel_prefix: near_you_production
